language: node_js

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
    - os: windows
    - os: osx

node_js:
  - "10"
cache:
  directories:
    - node_modules
addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - npm run build
  - xvfb-run npm run e2e
